### PR TITLE
Now one for python

### PR DESCRIPTION
**Pull request by hexylena**
Pretty [boring notebook](http://nbviewer.ipython.org/github/erasche/notebooks/blob/master/Python/python_package_to_galaxy_tool_dependency.ipynb), sorry. My python script also fetches the documentation from the library and automatically uses that as the README. I like that feature because I hate writing documentation for wrappers

### CODE REVIEW

**Comment by hexylena** [comment]
@bgruening you want this PR? :)

**Comment by bgruening** [comment]
Ha! Sure! This is great! Soon we have everything together for the final idea in this small project:

@erasche what about a small webservice with an API to send the package name language and get back the xml file. With this in place we can put it into planemo.

(Again: not sure this is worth the effort if we will migrate to brew/conda)

**Comment by bgruening** [comment]
Sorry, for being so silent lately, have 2 weeks workshop ahead ... First docker Galaxy based workshop with IPython ...

**Comment by hexylena** [comment]
No worries, you're awful busy, I understand. :) I'm finally having time for things, hence the dozens of bug reports and PRs.

I've been thinking about that sort of API service a LOT for "give me software X packaged for Y". Definitely worth looking into the "packaged for Galaxy" subset, a service like that would make tool-dev easier. I might throw something together soon, we'll see...

**Comment by hexylena** [comment]
@bgruening R will make our life easy...we can open an R session and call `library("X"); citation("X")` and get citations back :D

**Comment by hexylena** [comment]
Also, question. What about recursive generation. Currently, we take a "base package" that's of general interest like BioPerl, and then just download `.tar.gz`s for all the dependencies, not making them into packages. Should we be repackaging those and generating `tool_dependencies.xml` for those?

**Comment by hexylena** [comment]
Including @nitesh1989, since he's currently converting BioConductor R vignettes and I'm assuming making tools out of them.

**Comment by bgruening** [comment]
@erasche what do you mean with repacking?

**Comment by hexylena** [comment]
E.g. if you request `HTTP::Client` in perl, you'd get:

```
#main package
package_perl_http_client_1_57/tool_dependencies.xml
#repacked deps
package_perl_io_html_1_0001/tool_dependencies.xml
package_perl_http_date_6_02/tool_dependencies.xml
....
```

so that we're properly making re-use of things. I dunno, it's probably more hassle than it's worth, compared to existing method of just downloading .tar.gzs for depedent packages.

**Comment by bgruening** [comment]
Imho this is more work than worth it. At least for every package. For big projects like bioperl or expat this can be different. I would like to advertise these packages for reuse and not using this script to yet again include all XML libs. Not sure how we can communicate this.

**Comment by hexylena** [comment]
okay, just wanted to get your thoughts on that :) 

agreed, for reuse is best. I don't know either. hopefully we'll have an answer by the time it gets integrated into planemo :P

**Comment by bgruening** [comment]
;) I will try to get this Docker container done asap.

Have updated the readme, please complain ;)

**Comment by hexylena** [comment]
Hah! I'd been thinking about doing that for the past week and just never got around to it. Thanks for adding the links :)

**Pull request merged**
