### PR TITLE
Perl script as notebook alternative

### PR DESCRIPTION
**Pull request by hexylena**
Provides a simple perl script to handle the entire functionality of the notebook.

There may be a better place for it than your "notebooks" repository, but this was the only place I knew of to look for the perl module builder.

### CODE REVIEW

**Comment by bgruening** [comment]
Ha, thanks! If you create a notebook that calls this script, it fits quite well :)

**Comment by hexylena** [comment]
Yep, can do!

**Comment by hexylena** [comment]
@bgruening [notebook](http://nbviewer.ipython.org/github/erasche/notebooks/blob/master/Perl/perl_package_to_galaxy_tool_dependency_v2.ipynb) added.

**Comment by bgruening** [comment]
Very cool! Thanks a lot!

**Pull request merged**
